### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by kojq** [dmyTRUEk/gensoquote#5]
regarding AUR (`-git` is in!)

**Comment by dmyTRUEk** [comment]
Wow, that was very fast! I tested it, looks like it works, that's awesome!!

**Comment by dmyTRUEk** [comment]
Done in [this commit](https://github.com/dmyTRUEk/gensoquote/commit/f46072ae5bfbcf80cba2bec06e5630bccd184b97) (forgot to mention issue in commit)
